version: '3.8'
services:
  server:
    build:
      # context also sets where the image will be built
      # here, it must be set to the directory where the .yaml file is
      # because the nginx and src folder (referenced in the docker file)
      # are also located here
      context: .
      dockerfile: dockerfiles/nginx.dockerfile
    ports:
      - '8000:80'
    volumes:
    #:ro -> read-only
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ./src:/var/www/html
    depends_on:
      - php-interpreter
      - mysql
  php-interpreter:
    build:
      context: .
      dockerfile: dockerfiles/php.dockerfile
    volumes:
      # :delegated -> not updated inmediatly but processed in batches to improve performace
      - ./src:/var/www/html
  mysql:
    image: 'mysql:5.7'
    env_file:
      - ./env/mysql.env
  composer:
    build:
      context: ./dockerfiles
      dockerfile: composer.dockerfile
    volumes:
      - ./src:/var/www/html
  artisan:
    build:
      context: .
      dockerfile: dockerfiles/php.dockerfile
    volumes:
      - ./src:/var/www/html
    entrypoint: ['php', '/var/www/html/artisan']
  npm:
    image: node:14
    working_dir: /var/www/html
    entrypoint: ['npm']
    volumes:
      - ./src:/var/www/html